### ISSUE TITLE
Link to Linux interface is broken

### ISSUE THREAD

**Issue by tysonite** [intrepidcs/neoVI_API_Docs#1]
https://github.com/intrepidcs/neoVI_API_Docs/blob/59548566d5d2126831e5f345b382c3834fd0b364/README.md?plain=1#L14

It seems that link to Linux interface is broken, if you click it, it redirects to [intrepid.com](https://intrepidcs.com/) rather than to some page describing Linux interface.

**Comment by PBawane-Intrepid** [comment]
In the old API documentation, we have already checked. But it shows the same redirection to [https://intrepidcs.com](https://intrepidcs.com). @ARughani-Intrepid Can we confirm it from DC? So that we can fix it and close these issues.

**Comment by ARughani-Intrepid** [comment]
@tysonite and @PBawane-Intrepid the replacement for this documentation is our libicsneo. https://github.com/intrepidcs/libicsneo 

You can read our step by step guide at https://intrepidcs.com/the-easy-way-to-program-valuecan-4-in-python-using-raspberry-pi-linux/ 

@PBawane-Intrepid please update the link to https://github.com/intrepidcs/libicsneo
