### ISSUE TITLE
Include CANFD statusbitfield values

### ISSUE THREAD

**Issue by sangeetha-ponnusamy** [intrepidcs/neoVI_API_Docs#5]
//Spy Status Bitfield 3 constants CAN FD
const long SPY_STATUS3_CANFD_ESI = 0x01;
const long SPY_STATUS3_CANFD_IDE = 0x02;
const long SPY_STATUS3_CANFD_RTR = 0x04;
const long SPY_STATUS3_CANFD_FDF = 0x08;
const long SPY_STATUS3_CANFD_BRS = 0x10;

**Comment by sangeetha-ponnusamy** [comment]
https://github.com/intrepidcs/neoVI_API_Docs/commit/faf1e118616af2a864f6f6539a08f64276e18fef

**Comment by PBawane-Intrepid** [comment]
Requested changes are added please check @sangeetha-ponnusamy Please, let me know if anything needs to update. Thanks.
[https://docs.intrepidcs.com/neovi-api/win32-api-overview-intrepidcs-api/structures-types-and-defines-overview-intrepidcs-api/setting-structures-overview-intrepidcs-api/status-bitfields-neovi-api](url)
